### ISSUE TITLE
Fune-tuning model with quantization

### ISSUE THREAD

**Issue by anyaschenikova** [IlyaGusev/rulm#6]
I try to run fune-tuning of llama-7b, but it is too large for my 10Gb GPU and I am trying to fune-tune, for example, [4 bit version (which is only 4 Gb)](https://huggingface.co/wcde/llama-7b-4bit-gr128/tree/main) but the process just **killed** at the moment of loading weights. 

Is it really possible to run fune-tuning under such model, or it is even better to fine-tune whole llama-7b and then apply the quantization?

**Comment by IlyaGusev** [comment]
Hi! I'm not sure how you are supposed to train models in 4-bits. AFAIK only 8-bit training is commonly supported by now, although I haven't seen many full 8-bit fine tunes.

Usually, the easiest option is to train adapters, for instance, LoRA. In that case, you can quantize a model into 8 bits with mixed RTN quantization. It is natively supported in the transformers package. After that, you freeze the original weights and train only new weights.

**Comment by rakovskij-stanislav** [comment]
Hi! This project does support 4bit training - https://github.com/johnsmith0031/alpaca_lora_4bit

For now (started yesterday) I'm trying to combine rulm and alpaca_lora_4bit and check the outcome. As far as I can see, the fine-tune process will last less time. Unfortunately, alpaca_lora_4bit has no wandb integration. I'll write updates in this issue.

Also bitsandbytes announced 4bit support - https://www.reddit.com/r/LocalLLaMA/comments/13ahz60/bitsandbytes_4bit_finetuning_30b65b_llama_models/
Probably it's the easier way to get quantized models fine-tuning.

**Comment by rakovskij-stanislav** [comment]
I can say that alpaca_lora_4bit is nice. It has no cyrillic issues (xturing has), and I had no problems to run it.

The hardware: RTX A4000
The dataset is same for both cases.

Differences between rulm (using rualpaca 7b) and alpaca_lora_4bit (using GPTQ v2 alpaca 7b):
- The speed of fine-tuning: 26.3 hours vs 7.1, 10 batches vs 50 batches (trying to use the nearly whole 16gb vram)
- Eval/loss: 1.064 vs 1.214
- Inference: 15.2gb vs 5.7gb, the speed is 3-5 tokens vs 13 tokens
- Quality of speech: rualpaca is definitely better for russian speech. alpaca_lora_4bit often tries to use other languages or generates a code:

<img width="1052" alt="image" src="https://github.com/IlyaGusev/rulm/assets/25303578/83c86a07-670e-4358-a216-592fda821074">

For now, quantized model is more prefferable for me because I can get results faster - both inference and fine-tuning. Probably full training without lora will be also affordable on such small model.

It would be great if rulm will start to support alpaca_lora_4bit - 7b inference and fine_tuning can be fitted in 8gb vram, it's awesome result.

**Comment by IlyaGusev** [comment]
Thank you for sharing your results!

I'll definitely try to use code from alpaca_lora_4bit, though it seems to be highly experimental.
